--psql -U postgres

CREATE USER JpCodes WITH PASSWORD 'JpCodes';

CREATE DATABASE JpCodes OWNER JpCodes;

GRANT ALL PRIVILEGES ON DATABASE JpCodes TO JpCodes;

\c jpcodes

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO JpCodes;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO JpCodes;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON SEQUENCES TO JpCodes;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON FUNCTIONS TO JpCodes;

